typography_spectrum: 0.4507450133096427
color:
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
  brandStrength: 0.12483862019143999
  lightness: 0.8477470711804926
  saturation: 0.6521122746635228
  rhythmicContrast: 0.5891724082175642
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7239862293936312
analytics:
  google: UA-82146928-1
  facebook: null
  twitter: null
name: pk_henderson_
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: PATRICK + HENDERSON
purpose: []
