name: Patrick + Henderson
favicon: null
layout_spectrum: 0.42628
typography_spectrum: 0.36777
title: PATRICK+HENDERSON
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-82146928-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9834135128185153
  lightness: 0.775341352680698
  saturation: 0.4630518064368516
  rhythmicContrast: 0.8824444878846407
purpose: []
