typography_spectrum: 0.36777
color:
  brandColors:
    - '#4685aa'
    - '#ffbbbb'
    - '#d2421e'
    - '#ffffff'
    - '#000000'
  brandStrength: 0.9834135128185153
  lightness: 0.775341352680698
  saturation: 0.4630518064368516
  rhythmicContrast: 0.8824444878846407
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.42628
analytics:
  google: UA-82146928-1
  facebook: null
  twitter: null
name: Patrick + Henderson
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: PATRICK+HENDERSON
purpose: []
